# Generated by Django 5.2.7 on 2025-10-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acometidas',
            fields=[
                ('id_acometida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_acometida', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'acometidas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id_descuento', models.AutoField(primary_key=True, serialize=False)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'descuentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dr',
            fields=[
                ('id_dr', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_dr', models.CharField(max_length=100, unique=True)),
                ('valor_dr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_dr_empresa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'dr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instalaciones',
            fields=[
                ('id_instalacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_instalacion', models.DateField()),
                ('direccion', models.TextField()),
                ('numero_ot', models.CharField(max_length=50, unique=True)),
                ('eq_reutilizado', models.BooleanField(blank=True, null=True)),
                ('eq_retirado', models.BooleanField(blank=True, null=True)),
                ('metros_cable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('valor_añadido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_opcional_empresa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_dr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_orden', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_orden_empresa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_dr_empresa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('instalacion_compartida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total_empresa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'instalaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operadores',
            fields=[
                ('id_ope', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_operador', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'operadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('producto_serie', models.CharField(max_length=100, unique=True)),
                ('cantidad', models.IntegerField()),
                ('fecha_asignacion', models.DateField()),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id_unico_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('id_tecnico', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tecnicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodeordenes',
            fields=[
                ('id_tipo_orden', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_orden', models.CharField(max_length=100)),
                ('valor_orden', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_orden_empresa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tipodeordenes',
                'managed': False,
            },
        ),
    ]
